### ISSUE TITLE
Timeout error bug

### ISSUE THREAD

**Issue by IlanIwumbwe** [chinjyanson/SmartGrid#28]
```80, 52, 115, 152, 120, 119, 129, 99, 91, 81, 57, 106, 49, 71, 59, 28, 57] £/kWh
/home/ilan/Desktop/SmartGrid/.venv/lib/python3.11/site-packages/cvxpy/expressions/constants/constant.py:53: UserWarning: Initializing a Constant with a nested list is undefined behavior. Consider using a numpy array instead.
  warnings.warn(NESTED_LIST_WARNING)
Traceback (most recent call last):
  File "/home/ilan/Desktop/SmartGrid/buy_sell_algorithm/algo_driver.py", line 210, in <module>
    algo.driver(q)
  File "/home/ilan/Desktop/SmartGrid/buy_sell_algorithm/algo_driver.py", line 183, in driver
    time_taken, storage = self.something_else(storage)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ilan/Desktop/SmartGrid/buy_sell_algorithm/algo_driver.py", line 143, in something_else
    profit, storage = test.maximize_profit_mpc(storage, self.data_buffers, self.predictions, self.tick, 60-self.tick, )
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ilan/Desktop/SmartGrid/buy_sell_algorithm/test3.py", line 54, in maximize_profit_mpc
    profit = cp.sum(cp.multiply(neg_energy_transactions, predicted_sell_prices[t:t + horizon]) - cp.multiply(pos_energy_transactions, predicted_buy_prices[t:t + horizon]))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ilan/Desktop/SmartGrid/.venv/lib/python3.11/site-packages/cvxpy/atoms/affine/binary_operators.py", line 243, in __init__
    lh_expr, rh_expr = self.broadcast(lh_expr, rh_expr)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ilan/Desktop/SmartGrid/.venv/lib/python3.11/site-packages/cvxpy/expressions/expression.py", line 571, in broadcast
    rh_expr = Expression.cast_to_const(rh_expr)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ilan/Desktop/SmartGrid/.venv/lib/python3.11/site-packages/cvxpy/expressions/expression.py", line 564, in cast_to_const
    return expr if isinstance(expr, Expression) else cvxtypes.constant()(expr)
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ilan/Desktop/SmartGrid/.venv/lib/python3.11/site-packages/cvxpy/expressions/constants/constant.py", line 55, in __init__
    self._value = intf.DEFAULT_INTF.const_to_matrix(value)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ilan/Desktop/SmartGrid/.venv/lib/python3.11/site-packages/cvxpy/interface/numpy_interface/ndarray_interface.py", line 50, in const_to_matrix
    result = numpy.asarray(value).T
             ^^^^^^^^^^^^^^^^^^^^
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (42,) + inhomogeneous part.```

Not 100% sure about how to solve this, but it sometimes happens when we get a timeout error

**Comment by IlanIwumbwe** [comment]
Apparently not always at timeout, so something else is going wrong
```
Current tick 0
Cycle  1

Current predictions are ready
Timeout Error: Using cache
[{'end': 59, 'energy': 50.0, 'start': 0}, {'end': 59, 'energy': 21.708766717764327, 'start': 41}, {'end': 52, 'energy': 33.71897851143473, 'start': 25}]
  Get Energy In: 0.0 kWh
  Get Energy Used: [0.0, 2.2116682094699627, 0.0, 1.2966845118167074, 1.1481079557806548, 0.5937747392166121, 0.0, 0.4823083281632507, 1.6847183336251539, 1.218994210185183, 1.4933057846559357, 0.3275075945997293, 0.10952053505739878, 1.881895117651766, 0.5022351155558499, 0.6824618268569196, 0.590828426671495, 0.6101575566128439, 1.2177778838024353, 0.9974170579330831, 3.9371477895356746, 1.6285224001513123, 0.98494618902281, 1.302089261552302, 0.7932549282359871, 2.0065219727234576, 2.3556894322318214, 0.3647215863304578, 1.6600816076571747, 1.9808838406604614, 2.005167704916888, 2.481225656822411, 2.0992140401367894, 2.781590130577357, 2.1475611022787975, 1.9880013968446448, 2.908732575404292, 0.0, 3.84982375267048, 2.3104036960390317, 1.916210601376318, 1.5646007513007312, 3.0020076697832696, 3.3979885870067337, 2.450139002303421, 1.9893358775605599, 3.023787946327827, 1.39355253526043, 0.8368291397336214, 1.7107643349900445, 1.770577440281217, 3.0562972402281003, 1.031790665351784, 2.33833963418582, 1.0423644959182516, 1.7627594570178249, 0.5673475767143759, 1.7328901538699997, 0.0, 0.0] kWh
  Get Buy Price: [6, 34, 8, 25, 23, 18, 5, 17, 29, 24, 27, 17, 18, 37, 26, 30, 26, 24, 27, 22, 49, 22, 11, 11, 5, 12, 13, 5, 5, 5, 5, 10, 7, 15, 10, 11, 24, 5, 40, 29, 29, 30, 50, 58, 54, 54, 65, 48, 43, 52, 52, 63, 40, 51, 36, 41, 27, 36, 16, 5] £/kWh
  Get Sell Price: [13, 69, 17, 50, 47, 36, 10, 34, 58, 49, 54, 35, 36, 75, 53, 60, 53, 48, 55, 45, 99, 44, 23, 22, 10, 24, 26, 10, 10, 10, 10, 20, 14, 30, 21, 23, 48, 10, 80, 58, 59, 61, 100, 117, 109, 109, 130, 97, 86, 104, 105, 126, 81, 102, 72, 82, 54, 72, 32, 10] £/kWh
/home/ilan/Desktop/SmartGrid/.venv/lib/python3.11/site-packages/cvxpy/expressions/constants/constant.py:53: UserWarning: Initializing a Constant with a nested list is undefined behavior. Consider using a numpy array instead.
  warnings.warn(NESTED_LIST_WARNING)
Traceback (most recent call last):
  File "/home/ilan/Desktop/SmartGrid/buy_sell_algorithm/algo_driver.py", line 211, in <module>
    algo.driver(q)
  File "/home/ilan/Desktop/SmartGrid/buy_sell_algorithm/algo_driver.py", line 172, in driver
    tt, storage = self.something_else(storage)  # new cycle should always come before something_else such that data buffers get emptied
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ilan/Desktop/SmartGrid/buy_sell_algorithm/algo_driver.py", line 144, in something_else
    profit, storage = test.maximize_profit_mpc(storage, self.data_buffers, self.predictions, self.tick, 60-self.tick, )
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ilan/Desktop/SmartGrid/buy_sell_algorithm/test3.py", line 54, in maximize_profit_mpc
    profit = cp.sum(cp.multiply(neg_energy_transactions, predicted_sell_prices[t:t + horizon]) - cp.multiply(pos_energy_transactions, predicted_buy_prices[t:t + horizon]))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ilan/Desktop/SmartGrid/.venv/lib/python3.11/site-packages/cvxpy/atoms/affine/binary_operators.py", line 243, in __init__
    lh_expr, rh_expr = self.broadcast(lh_expr, rh_expr)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ilan/Desktop/SmartGrid/.venv/lib/python3.11/site-packages/cvxpy/expressions/expression.py", line 571, in broadcast
    rh_expr = Expression.cast_to_const(rh_expr)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ilan/Desktop/SmartGrid/.venv/lib/python3.11/site-packages/cvxpy/expressions/expression.py", line 564, in cast_to_const
    return expr if isinstance(expr, Expression) else cvxtypes.constant()(expr)
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ilan/Desktop/SmartGrid/.venv/lib/python3.11/site-packages/cvxpy/expressions/constants/constant.py", line 55, in __init__
    self._value = intf.DEFAULT_INTF.const_to_matrix(value)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ilan/Desktop/SmartGrid/.venv/lib/python3.11/site-packages/cvxpy/interface/numpy_interface/ndarray_interface.py", line 50, in const_to_matrix
    result = numpy.asarray(value).T
             ^^^^^^^^^^^^^^^^^^^^
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (60,) + inhomogeneous part.
```
